[package]
name = "quizdown-cli"
version = "0.1.0"
authors = ["John Foley <jjfoley@smith.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quizdown = {path="../lib"}
clap = "2.33"